# Generated by Django 5.2.8 on 2025-12-02 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('reading_level', models.CharField(blank=True, max_length=100, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('openlibrary', 'OpenLibrary'), ('openai', 'OpenAI')], default='openlibrary', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='catalog.book')),
            ],
        ),
    ]
