# Generated by Django 5.2.8 on 2025-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ai_preview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
