# Generated by Django 5.2.8 on 2025-12-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_ai_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpreview',
            name='openlibrary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookpreview',
            name='preview_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookpreview',
            name='real_isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
