# Generated by Django 5.2.8 on 2025-12-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookpreview_openlibrary_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookpreview',
            name='real_isbn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
