# Generated by Django 5.2.8 on 2025-12-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_isbn_alter_bookpreview_real_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ol_work_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
