# Generated by Django 5.2.8 on 2025-12-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_ol_work_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ol_work_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='real_isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
