# Generated by Django 5.2.8 on 2025-12-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_book_ol_work_id_alter_book_real_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrowed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
