# Generated by Django 5.2.8 on 2025-12-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_bookinstance_borrowed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpreview',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookpreview',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
